[package]
name = "func_lang"
version = "0.1.0"
edition = "2021"

[dependencies]
codespan-reporting = "0.11.1"
nom = "7.1.3"
nom_locate = "4.2.0"

[features]
default = ["safe_mode"]
safe_mode = []
unsafe_mode = []
